<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>lampacker</ToolCommandName>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="System.CommandLine" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\DotnetHelper\DotnetHelper.csproj" />
      <ProjectReference Include="..\Laminar.PluginFramework.Json\Laminar.PluginFramework.Json.csproj" />
    </ItemGroup>
    
</Project>
