//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laminar.Avalonia.Assets.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laminar.Avalonia.Assets.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Script.
        /// </summary>
        public static string AddScript {
            get {
                return ResourceManager.GetString("AddScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Storage Item.
        /// </summary>
        public static string AddStorageItem {
            get {
                return ResourceManager.GetString("AddStorageItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Settings.
        /// </summary>
        public static string CloseSettingsMenu {
            get {
                return ResourceManager.GetString("CloseSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Sidebar.
        /// </summary>
        public static string CloseSidebar {
            get {
                return ResourceManager.GetString("CloseSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Item.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Folder.
        /// </summary>
        public static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Script.
        /// </summary>
        public static string DeleteScript {
            get {
                return ResourceManager.GetString("DeleteScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable this folder.
        /// </summary>
        public static string DisableFolder {
            get {
                return ResourceManager.GetString("DisableFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable this script.
        /// </summary>
        public static string DisableScript {
            get {
                return ResourceManager.GetString("DisableScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable this folder.
        /// </summary>
        public static string EnableFolder {
            get {
                return ResourceManager.GetString("EnableFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable this script.
        /// </summary>
        public static string EnableScript {
            get {
                return ResourceManager.GetString("EnableScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Sidebar.
        /// </summary>
        public static string ExpandSidebar {
            get {
                return ResourceManager.GetString("ExpandSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Navigator Tools.
        /// </summary>
        public static string FileNavigatorTools {
            get {
                return ResourceManager.GetString("FileNavigatorTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Tools.
        /// </summary>
        public static string FolderTools {
            get {
                return ResourceManager.GetString("FolderTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        public static string OpenSettingsMenu {
            get {
                return ResourceManager.GetString("OpenSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Tools.
        /// </summary>
        public static string ScriptTools {
            get {
                return ResourceManager.GetString("ScriptTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StorageItemTools.
        /// </summary>
        public static string StorageItemTools {
            get {
                return ResourceManager.GetString("StorageItemTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Enabled.
        /// </summary>
        public static string ToggleEnabled {
            get {
                return ResourceManager.GetString("ToggleEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open/Close Settings Menu.
        /// </summary>
        public static string ToggleSettingsMenu {
            get {
                return ResourceManager.GetString("ToggleSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Sidebar.
        /// </summary>
        public static string ToggleSidebar {
            get {
                return ResourceManager.GetString("ToggleSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
    }
}
