name: Laminar-Runner-CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for nbgv versioning

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Ensure local NuGet feed exists
        run: mkdir -p .nuget.local
          
      - name: Build plugin source generators
        run: dotnet build src/PluginFramework/Laminar.PluginFramework.SourceGeneration/Laminar.PluginFramework.SourceGeneration.csproj

      - name: Build plugin framework
        run: dotnet build src/PluginFramework/Laminar.PluginFramework/Laminar.PluginFramework.csproj

      - name: Restore solution
        run: dotnet restore

      - name: Build Runner
        run: dotnet build -c Debug

      - name: Run Tests
        run: dotnet test --no-build -c Debug --verbosity normal

      - name: Install xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Smoke test application startup
        run: |
          set +e
      
          timeout 20s xvfb-run dotnet run \
            --project build/Laminar.Runner/Laminar.Runner.csproj \
            --configuration Debug
      
          EXIT_CODE=$?
      
          if [ $EXIT_CODE -eq 124 ]; then
            echo "Smoke test timed out as expected."
            exit 0
          fi
      
          exit $EXIT_CODE
